{'kind': 'books#volumes',
'totalItems': 1,
'items': [{'kind': 'books#volume',
          'id': 'Osn8ugAACAAJ',
          'etag': 'WlgrcGTMHoU',
          'selfLink': 'https://www.googleapis.com/books/v1/volumes/Osn8ugAACAAJ', 
          'volumeInfo': {'title': 'Reckoning',
                        'subtitle': 'The Quarter Boys',
                        'authors': ['David Lennon'],
                        'publisher': 'Createspace Indie Pub Platform',
                        'publishedDate': '2012-04-01',
                        'description': "After two years of near-constant upheaval in their professional and personal lives, private investigators Michel Doucette and Alexandra “Sassy” Jones have finally found some peace. For Michel, in particular, everything is near-idyllic, as he and his boyfriend, Joel, build a life together and search for a new home for themselves and their dog, Blue. But when Michel receives a mysterious ransom note, things quickly change, and he and Sassy find themselves at the center of a police investigation. As old friends and enemies suddenly reappear, it becomes all too clear that the past isn't quite done with them yet.Reckoning is the fifth novel featuring detectives Michel Doucette and Sassy Jones.",
                        'readingModes': {'text': False,
                                        'image': False},
                        'maturityRating': 'NOT_MATURE',
                        'allowAnonLogging': False,
                        'contentVersion': 'preview-1.0.0',
                        'imageLinks': {'smallThumbnail': 'http://books.google.com/books/content?id=Osn8ugAACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api',
                        'thumbnail': 'http://books.google.com/books/content?id=Osn8ugAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api'}, 'previewLink': 'http://books.google.com/books?id=Osn8ugAACAAJ&dq=intitle:reckoning%2Binauthor:david%2Binauthor:lennon&hl=&cd=1&source=gbs_api',
                        'infoLink': 'http://books.google.com/books?id=Osn8ugAACAAJ&dq=intitle:reckoning%2Binauthor:david%2Binauthor:lennon&hl=&source=gbs_api',
                        'canonicalVolumeLink': 'https://books.google.com/books/about/Reckoning.html?hl=&id=Osn8ugAACAAJ'},
                        'saleInfo': {'country': 'US'},
                        'accessInfo': {'country': 'US',
                        'epub': {'isAvailable': False},
                        'pdf': {'isAvailable': False},
                        'accessViewStatus': 'NONE'},
                        'searchInfo': {'textSnippet': 'As old friends and enemies suddenly reappear, it becomes all too clear that the past isn&#39;t quite done with them yet. Reckoning is the fifth novel featuring detectives Michel Doucette and Sassy Jones.'}
            }]
}
